import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Momentum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl mx-auto my-12">
        <section className="relative py-4">
          <div className="container mx-auto">
            <div className="rounded-xl shadow-xl flex divide-y bg-gradient-to-br from-blue-900 to-indigo-500">
              <div className="p-8 flex-grow">
                <h1 className="text-3xl text-white font-bold">Momentum</h1>
              </div>
              <div className="p-8 flex-grow">
                <button className="bg-action p-3 font-bold text-primary rounded-2xl">Get Started</button>
              </div>
            </div>
          </div>
        </section>
      </main>
       
    </>
  );
};

export default Home;
